version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy-gamp
    ports:
      - '81:81'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server-DVgamp
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - pg
    depends_on:
      - pg
  pg:
    image: bitnami/postgresql:11-debian-9
    container_name: pg-gamp
    environment:
      POSTGRESQL_USERNAME: luis
      POSTGRESQL_PASSWORD: gampdatabase
      POSTGRESQL_DATABASE: bdgamp
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
